Fix implicit declaration of parse_version in libopkg/opkg.c
opkg.c: In function 'opkg_compare_versions':
opkg.c:882:3: warning: implicit declaration of function 'parse_version' [-Wimplicit-function-declaration]

The required function is declared in "pkg_parse.h"

Signed-off-by: Paul Barker <paul@paulbarker.me.uk>

git-svn-id: http://opkg.googlecode.com/svn/trunk@678 e8e0d7a0-c8d9-11dd-a880-a1081c7ac358